spring:
  application:
    name: library
  datasource:
    url: jdbc:postgresql://localhost:5432/biblioteca
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        show_sql: true

#      update, none , create-drop