spring:

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  application:
    name: library
  datasource:
    url: jdbc:postgresql://localhost:5432/biblioteca
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

properties:
      hibernate:
        show_sql: true

kind: Application

#      update, none , create-drop