spring:
  application:
    name: library
  datasource:
    url: jdbc:postgresql://localhost:5432/biblioteca
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#      update, none , create-drop